Fix deprecation
org.gradle.api.GradleException: Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0
	at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:87)
	at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:341)
	at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:241)
	at org.gradle.internal.deprecation.DeprecationMessageBuilder$WithDocumentation.nagUser(DeprecationMessageBuilder.java:189)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.logGroovySpaceAssignmentDeprecation(AsmBackedClassGenerator.java:262)
	at com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated.testBuildType(Unknown Source)