Fix AndroidBuildPluginIntgTest and KotlinPluginIntgTest
com.android.builder.errors.EvalIssueException: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
root project 'junit14860831367069665448' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32
	at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:111)
	at com.android.builder.errors.IssueReporter.reportError$default(IssueReporter.kt:107)
	at com.android.build.gradle.internal.utils.GradlePluginUtils.enforceMinimumVersionOfPlugin(GradlePluginUtils.kt:156)
	at com.android.build.gradle.internal.utils.GradlePluginUtils.access$enforceMinimumVersionOfPlugin(GradlePluginUtils.kt:1)
	at com.android.build.gradle.internal.utils.GradlePluginUtils$enforceMinimumVersionsOfPlugins$1$3.execute(GradlePluginUtils.kt:136)
	at com.android.build.gradle.internal.utils.GradlePluginUtils$enforceMinimumVersionsOfPlugins$1$3.execute(GradlePluginUtils.kt:133)