Integrate :plugin into the project (#142)
* Merge plugin into main project
* Centralize logging with a better verbose output
* Decouple test from common
* Decouple :plugin from kotlin gradle plugin
* Make android pluginVersion and compileSdkVersion configurable from Gradle execution.
* Decouple KotlinPlugin from Android Gradle Plugin
* Turn on publishing in :plugin
* Better error handling than NPE!! for description
* Make sure custom version is picked up when publishing.
* Support different JDKs and OSs.
* Improve compatibility of :plugin with AGP 4.x
* Force the right hamcrest library
* Getting a lot of errors similar to Caused by: java.lang.NoSuchMethodError: setMinSdkVersion(LApiVersion;)V so instead of calling the correct method via reflection (the property setters didn't exist in 4.0.x) opted to call the `setFoo(*)` variant.
* Centralize AGPVersion checks and use this in tests and production
* Use matrix.name in job names