Migrate build logic from deprecated Kotlin DSL APIs
Gradle 9.6.1 failed :plugins:compileKotlin because warnings are errors:

e: warnings found and -Werror specified
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/module/net.twisterrob.gradle.build.module.browser.gradle.kts:11:50 [DEPRECATION] ''fun provideDelegate(thisRef: Any?, property: KProperty<*>): ExistingDomainObjectDelegate<Configuration>'' is deprecated. Use ''val element = create(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/module/net.twisterrob.gradle.build.module.browser.gradle.kts:11:50 [DEPRECATION] ''fun <T : Any> NamedDomainObjectContainer<T>.creating(configuration: T.() -> Unit): NamedDomainObjectContainerCreatingDelegateProvider<T>'' is deprecated. Use ''val element = create(name) { }'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/module/net.twisterrob.gradle.build.module.browser.gradle.kts:11:50 [DEPRECATION] ''fun <T> ExistingDomainObjectDelegate<out T>.getValue(receiver: Any?, property: KProperty<*>): T'' is deprecated. Use the named() API instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/publishing/net.twisterrob.gradle.build.publish.gradle.kts:144:30 [DEPRECATION] ''fun Project.provideDelegate(any: Any?, property: KProperty<*>): PropertyDelegate'' is deprecated. Use ''val property = project.property(name)'' or ''val property = project.findProperty(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/publishing/net.twisterrob.gradle.build.publish.gradle.kts:146:35 [DEPRECATION] ''fun Project.provideDelegate(any: Any?, property: KProperty<*>): PropertyDelegate'' is deprecated. Use ''val property = project.property(name)'' or ''val property = project.findProperty(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/root/net.twisterrob.gradle.build.root.publishing.gradle.kts:19:45 [DEPRECATION] ''fun Project.provideDelegate(any: Any?, property: KProperty<*>): PropertyDelegate'' is deprecated. Use ''val property = project.property(name)'' or ''val property = project.findProperty(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/root/net.twisterrob.gradle.build.root.publishing.gradle.kts:22:37 [DEPRECATION] ''fun Project.provideDelegate(any: Any?, property: KProperty<*>): PropertyDelegate'' is deprecated. Use ''val property = project.property(name)'' or ''val property = project.findProperty(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/root/net.twisterrob.gradle.build.root.publishing.gradle.kts:23:37 [DEPRECATION] ''fun Project.provideDelegate(any: Any?, property: KProperty<*>): PropertyDelegate'' is deprecated. Use ''val property = project.property(name)'' or ''val property = project.findProperty(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/InitScriptMetadataPlugin.kt:34:44 [DEPRECATION] ''fun create(project: Project): ProjectDependency'' is deprecated. Deprecated in Java.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/net.twisterrob.gradle.build.testing.plugin-under-test-metadata-extras.gradle.kts:64:37 [DEPRECATION] ''fun provideDelegate(thisRef: Any?, property: KProperty<*>): ExistingDomainObjectDelegate<Configuration>'' is deprecated. Use ''val element = create(name)'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/net.twisterrob.gradle.build.testing.plugin-under-test-metadata-extras.gradle.kts:64:37 [DEPRECATION] ''fun <T : Any> NamedDomainObjectContainer<T>.creating(configuration: T.() -> Unit): NamedDomainObjectContainerCreatingDelegateProvider<T>'' is deprecated. Use ''val element = create(name) { }'' instead. See the Gradle 9.6 upgrading guide.
w: file:///.../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/net.twisterrob.gradle.build.testing.plugin-under-test-metadata-extras.gradle.kts:64:37 [DEPRECATION] ''fun <T> ExistingDomainObjectDelegate<out T>.getValue(receiver: Any?, property: KProperty<*>): T'' is deprecated. Use the named() API instead. See the Gradle 9.6 upgrading guide.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task '':plugins:compileKotlin''.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.btapi.BuildToolsApiCompilationWork
   > Compilation error. See log for more details

BUILD FAILED in 27s