Adapt version catalog loader for Gradle 9.6
Gradle 9.6.1 failed while loading settings:

FAILURE: Build failed with an exception.

* Where:
Settings file ''.../settings.gradle.kts'' line: 118

* What went wrong:
org.gradle.api.internal.catalog.DefaultVersionCatalogBuilder.getProblemService()

* Exception is:
java.lang.NoSuchMethodException: org.gradle.api.internal.catalog.DefaultVersionCatalogBuilder.getProblemService()
	at VersionCatalogBuilder_loadKt.load$lambda$0(versionCatalogBuilder-load.kt:25)
	at org.gradle.api.internal.catalog.parser.TomlCatalogFileParser.parse(TomlCatalogFileParser.java:166)
	at VersionCatalogBuilder_loadKt.load(versionCatalogBuilder-load.kt:27)
	at Settings_gradle.<init>(settings.gradle.kts:118)

BUILD FAILED in 45s

Changing to getProblemsService then failed because it is protected:

FAILURE: Build failed with an exception.

* Where:
Settings file ''.../settings.gradle.kts'' line: 118

* What went wrong:
class VersionCatalogBuilder_loadKt cannot access a member of class org.gradle.api.internal.catalog.DefaultVersionCatalogBuilder with modifiers "protected abstract"

* Exception is:
java.lang.IllegalAccessException: class VersionCatalogBuilder_loadKt cannot access a member of class org.gradle.api.internal.catalog.DefaultVersionCatalogBuilder with modifiers "protected abstract"
	at VersionCatalogBuilder_loadKt.load$lambda$0(versionCatalogBuilder-load.kt:25)
	at org.gradle.api.internal.catalog.parser.TomlCatalogFileParser.parse(TomlCatalogFileParser.java:166)
	at VersionCatalogBuilder_loadKt.load(versionCatalogBuilder-load.kt:27)
	at Settings_gradle.<init>(settings.gradle.kts:118)

BUILD FAILED in 20s