Fix missing method
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.provider.Provider org.gradle.api.reporting.Report.getOutputLocation()'
	at net.twisterrob.gradle.compat.GradleCompatKt.getOutputLocationCompat(GradleCompat.kt:294)
	at net.twisterrob.gradle.quality.gather.QualityTaskReportGatherer.getParsableReportLocation(QualityTaskReportGatherer.kt:23)