Use compatibility layer for accessing new compat var.
Caused by: java.lang.NoSuchMethodError: 'com.android.build.api.variant.AndroidTest com.android.build.api.variant.ApplicationVariant.getAndroidTest()'