Migrate test reporting to typed listeners
`gradlew -q jar --no-daemon --no-configuration-cache --stacktrace` failed with:

```
e: warnings found and -Werror specified
w: .../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/configureVerboseReportsForGithubActions.kt:36:2 [DEPRECATION] 'fun beforeSuite(closure: (Closure<Any!>..Closure<*>?)): Unit' is deprecated. Deprecated in Java.
w: .../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/configureVerboseReportsForGithubActions.kt:39:2 [DEPRECATION] 'fun beforeTest(closure: (Closure<Any!>..Closure<*>?)): Unit' is deprecated. Deprecated in Java.
w: .../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/configureVerboseReportsForGithubActions.kt:42:2 [DEPRECATION] 'fun onOutput(closure: (Closure<Any!>..Closure<*>?)): Unit' is deprecated. Deprecated in Java.
w: .../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/configureVerboseReportsForGithubActions.kt:105:2 [DEPRECATION] 'fun afterTest(closure: (Closure<Any!>..Closure<*>?)): Unit' is deprecated. Deprecated in Java.
w: .../gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/testing/configureVerboseReportsForGithubActions.kt:108:2 [DEPRECATION] 'fun afterSuite(closure: (Closure<Any!>..Closure<*>?)): Unit' is deprecated. Deprecated in Java.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 14s
```