Ignore AGP Project dependency notation warning
Gradle 9.6.1 CI failed while verifying docs/examples/release:

Using a Project object as a dependency notation has been deprecated. This will fail with an error in Gradle 10. Please use the project(String) method on DependencyHandler or the createProjectDependency(String) method on DependencyFactory instead. Consult the upgrading guide for further information: https://docs.gradle.org/9.6.1/userguide/upgrading_version_9.html#dependency_project_notation
	at org.gradle.api.internal.notations.DependencyProjectNotationConverter.convert(DependencyProjectNotationConverter.java:48)
	at org.gradle.api.internal.notations.DependencyProjectNotationConverter.convert(DependencyProjectNotationConverter.java:29)
	at com.android.build.gradle.internal.dependency.VariantDependenciesBuilder.build(VariantDependenciesBuilder.java:279)
	at com.android.build.gradle.internal.VariantManager.createTestComponents(VariantManager.kt:654)
	at com.android.build.gradle.internal.VariantManager.createVariantsFromCombination(VariantManager.kt:826)

FAILURE: Build failed with an exception.

* What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 10

* Exception is:
org.gradle.api.GradleException: Deprecated Gradle features were used in this build, making it incompatible with Gradle 10
	at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:86)
	at org.gradle.api.internal.notations.DependencyProjectNotationConverter.convert(DependencyProjectNotationConverter.java:48)
	at com.android.build.gradle.internal.dependency.VariantDependenciesBuilder.build(VariantDependenciesBuilder.java:279)

BUILD FAILED in 1m 26s