Getting a lot of errors similar to
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.internal.dsl.DefaultConfig.setMinSdkVersion(Lcom/android/builder/model/ApiVersion;)V

so instead of calling the correct method via reflection (the property setters didn't exist in 4.0.x) opted to call the `setFoo(*)` variant.